# Assignment 2

# Singular Value Decomposition (SVD)

Name :- Neha Gupta

Enrollment no:- 2021MSBDA023

Submitted to:- Dr. Pritpal Singh Sir

In [214]:
#Read Dataset
read=pd.read_csv("temp_data.csv")
read

<IPython.core.display.Javascript object>

Temp  Wind
0     20    12
1     17    14
2     18    13
3     14    15
4     15    16
5     16    18
6     17    19
7     21    11
8     22    14
9     13    17
10    12    15
11    12    29
12    35    28
13    35    27
14    25    26
15    21    25
16    23    24
17    12    23
18    11    22
19    19    21
20    18    11
21    33    12
22    32    13
23    21    14
24    25    15
25    34    16
26    27    17
27    28    18
28    29    19
29    30    20

In [215]:
#Load Dataset as Matrix
matrix=read.to_numpy()
matrix

array([[20, 12],
       [17, 14],
       [18, 13],
       [14, 15],
       [15, 16],
       [16, 18],
       [17, 19],
       [21, 11],
       [22, 14],
       [13, 17],
       [12, 15],
       [12, 29],
       [35, 28],
       [35, 27],
       [25, 26],
       [21, 25],
       [23, 24],
       [12, 23],
       [11, 22],
       [19, 21],
       [18, 11],
       [33, 12],
       [32, 13],
       [21, 14],
       [25, 15],
       [34, 16],
       [27, 17],
       [28, 18],
       [29, 19],
       [30, 20]], dtype=int64)

In [216]:
#find transpose of given matrix
transpose = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
print("Transpose is:- ")
for transposed in transpose:
    print(transposed)

Transpose is:- 
[20, 17, 18, 14, 15, 16, 17, 21, 22, 13, 12, 12, 35, 35, 25, 21, 23, 12, 11, 19, 18, 33, 32, 21, 25, 34, 27, 28, 29, 30]
[12, 14, 13, 15, 16, 18, 19, 11, 14, 17, 15, 29, 28, 27, 26, 25, 24, 23, 22, 21, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [217]:
square =  [[sum(first*second for first,second in zip(X_rows,Y_column)) for Y_column in zip(*transpose)] for X_rows in matrix]
print("Square Matrix is:- ")
for dot in square:
    print(dot)

Square Matrix is:- 
[544, 508, 516, 460, 492, 536, 568, 552, 608, 464, 420, 588, 1036, 1024, 812, 720, 748, 516, 484, 632, 492, 804, 796, 588, 680, 872, 744, 776, 808, 840]
[508, 485, 488, 448, 479, 524, 555, 511, 570, 459, 414, 610, 987, 973, 789, 707, 727, 526, 495, 617, 460, 729, 726, 553, 635, 802, 697, 728, 759, 790]
[516, 488, 493, 447, 478, 522, 553, 521, 578, 455, 411, 593, 994, 981, 788, 703, 726, 515, 484, 615, 467, 750, 745, 560, 645, 820, 707, 738, 769, 800]
[460, 448, 447, 421, 450, 494, 523, 459, 518, 437, 393, 603, 910, 895, 740, 669, 682, 513, 484, 581, 417, 642, 643, 504, 575, 716, 633, 662, 691, 720]
[492, 479, 478, 450, 481, 528, 559, 491, 554, 467, 420, 644, 973, 957, 791, 715, 729, 548, 517, 621, 446, 687, 688, 539, 615, 766, 677, 708, 739, 770]
[536, 524, 522, 494, 528, 580, 614, 534, 604, 514, 462, 714, 1064, 1046, 868, 786, 800, 606, 572, 682, 486, 744, 746, 588, 670, 832, 738, 772, 806, 840]
[568, 555, 553, 523, 559, 614, 650, 566, 640, 544, 489, 755, 1127, 110

In [218]:
eigenvalues, eigenvectors = np.linalg.eig(square)
idx = eigenvalues.argsort()[::-1]   
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:,idx]

<IPython.core.display.Javascript object>

In [219]:
eigenvalues

array([ 2.55640578e+04+0.00000000e+00j,  1.05694218e+03+0.00000000e+00j,
        8.79656997e-13+0.00000000e+00j,  1.98240298e-13+8.91046943e-14j,
        1.98240298e-13-8.91046943e-14j,  1.59786289e-13+0.00000000e+00j,
        1.02211856e-13+1.19922083e-13j,  1.02211856e-13-1.19922083e-13j,
        9.19760046e-14+3.78426324e-13j,  9.19760046e-14-3.78426324e-13j,
        8.82089051e-14+6.05417828e-14j,  8.82089051e-14-6.05417828e-14j,
        5.19740618e-14+7.62901208e-15j,  5.19740618e-14-7.62901208e-15j,
        2.19661086e-14+1.33861258e-13j,  2.19661086e-14-1.33861258e-13j,
        1.01602754e-15+0.00000000e+00j, -2.21570291e-14+0.00000000e+00j,
       -2.26067309e-14+4.17928183e-14j, -2.26067309e-14-4.17928183e-14j,
       -2.45648731e-14+5.62091880e-14j, -2.45648731e-14-5.62091880e-14j,
       -7.52494549e-14+1.67109945e-13j, -7.52494549e-14-1.67109945e-13j,
       -7.69727030e-14+0.00000000e+00j, -1.51008927e-13+0.00000000e+00j,
       -1.82204651e-13+8.78179756e-14j, -1.82204651

In [220]:
eigenvectors

array([[-1.44516697e-01+0.j        ,  9.77188834e-02+0.j        ,
        -2.38417181e-01+0.j        ,  1.76209043e-02+0.0076784j ,
         1.76209043e-02-0.0076784j , -1.38749082e-02+0.j        ,
         1.50633533e-02-0.00937856j,  1.50633533e-02+0.00937856j,
         2.93048127e-02-0.02705459j,  2.93048127e-02+0.02705459j,
        -2.23867643e-02+0.02737038j, -2.23867643e-02-0.02737038j,
         3.90055510e-02+0.01292814j,  3.90055510e-02-0.01292814j,
         2.16571742e-02-0.00757734j,  2.16571742e-02+0.00757734j,
         1.05667001e-02+0.j        , -2.95581445e-02+0.j        ,
         2.99863437e-02-0.00254307j,  2.99863437e-02+0.00254307j,
        -1.33301745e-02+0.03265169j, -1.33301745e-02-0.03265169j,
         2.85787591e-02-0.01786688j,  2.85787591e-02+0.01786688j,
         2.39586559e-02+0.j        , -4.58492457e-02+0.j        ,
        -1.09368046e-02+0.05205041j, -1.09368046e-02-0.05205041j,
        -8.42264085e-03+0.j        ,  3.62877645e-02+0.j        ],
       [-

In [221]:
#A'A
rev_trans=np.matmul(transpose,matrix)
rev_trans

<IPython.core.display.Javascript object>

array([[15945, 11967],
       [11967, 10676]], dtype=int64)

In [222]:
evalue,evec=np.linalg.eig(rev_trans)

<IPython.core.display.Javascript object>

In [223]:
#A'A Eigenvalue
evalue

array([25564.05782008,  1056.94217992])

In [224]:
#A'A Eigenvector
evec

array([[ 0.77942247, -0.62649869],
       [ 0.62649869,  0.77942247]])

In [225]:
vec_trans = np.transpose(evec)

<IPython.core.display.Javascript object>

In [226]:
vec_trans

array([[ 0.77942247,  0.62649869],
       [-0.62649869,  0.77942247]])

In [227]:
dia = np.diag(eigenvalues)
dia

<IPython.core.display.Javascript object>

array([[ 2.55640578e+04+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00

In [228]:
remove = np.delete(dia,np.s_[2:31],axis=1)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [229]:
remove

array([[25564.05782008+0.j,     0.        +0.j],
       [    0.        +0.j,  1056.94217992+0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j],
       [    0.      

In [230]:
#This is sigma:- 
rem = np.sqrt(remove)
rem

<IPython.core.display.Javascript object>

array([[159.88764124+0.j,   0.        +0.j],
       [  0.        +0.j,  32.51064718+0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  0.        +0.j,   0.        +0.j],
       [  

In [231]:
result = eigenvectors@rem@vec_trans
abs(result)

array([[20., 12.],
       [17., 14.],
       [18., 13.],
       [14., 15.],
       [15., 16.],
       [16., 18.],
       [17., 19.],
       [21., 11.],
       [22., 14.],
       [13., 17.],
       [12., 15.],
       [12., 29.],
       [35., 28.],
       [35., 27.],
       [25., 26.],
       [21., 25.],
       [23., 24.],
       [12., 23.],
       [11., 22.],
       [19., 21.],
       [18., 11.],
       [33., 12.],
       [32., 13.],
       [21., 14.],
       [25., 15.],
       [34., 16.],
       [27., 17.],
       [28., 18.],
       [29., 19.],
       [30., 20.]])

matrix = U * W * V'